<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="SMSL187" name="suiteTest.Regresion_Socio_Mail" tests="1" failures="1" timestamp="08 oct 2019 14:39:28 GMT" time="122.852" errors="0">
  <testcase name="S_RealizarVC_02" time="122.852" classname="suiteTest.Regresion_Socio_Mail">
    <failure type="java.lang.AssertionError" message="Fallo test - S_RealizarVC_02 - Step: 09_Pantalla Agradecimiento - Visualizar">
      <![CDATA[java.lang.AssertionError: Fallo test - S_RealizarVC_02 - Step: 09_Pantalla Agradecimiento - Visualizar
	at org.testng.Assert.fail(Assert.java:93)
	at steps.S_RealizarVC_NotificacionStep.Run(S_RealizarVC_NotificacionStep.java:86)
	at suiteTest.Regresion_Socio_Mail.S_RealizarVC_02(Regresion_Socio_Mail.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- S_RealizarVC_02 -->
</testsuite> <!-- suiteTest.Regresion_Socio_Mail -->
