<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SMSL187" ignored="0" name="Realizar VC - Mobile" tests="1" failures="1" timestamp="08 oct 2019 14:53:20 GMT" time="112.173" errors="0">
  <testcase name="S_RealizarVC_02" time="89.208" classname="suiteTest.Regresion_Socio_Mail">
    <failure type="java.lang.AssertionError" message="Fallo test - S_RealizarVC_02 - Step: 09_Pantalla Agradecimiento - Visualizar">
      <![CDATA[java.lang.AssertionError: Fallo test - S_RealizarVC_02 - Step: 09_Pantalla Agradecimiento - Visualizar
	at steps.S_RealizarVC_NotificacionStep.Run(S_RealizarVC_NotificacionStep.java:86)
	at suiteTest.Regresion_Socio_Mail.S_RealizarVC_02(Regresion_Socio_Mail.java:15)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- S_RealizarVC_02 -->
</testsuite> <!-- Realizar VC - Mobile -->
